defaults:
  - default.yaml

# NOTE: https://github.com/facebookresearch/hydra/issues/2070
# for improved Hydra + Lightning + DDP support is not merged yet
strategy: ddp_with_xpu

accelerator: xpu
devices: 8
num_nodes: 1
sync_batchnorm: True
